apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhnmrt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dhnmrt
  template:
    metadata:
      labels:
        app: dhnmrt
    spec:
      containers:
      - image: okteto.dev/dhnmrt:latest
        name: dhnmrt
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "7d634231-6c35-4c59-b548-d342cd6496f1"
        - name: Vless_Path
          value: "/vl5dveth55"
        - name: Vmess_UUID
          value: "7d634231-6c35-4c59-b548-d342cd6496f1"
        - name: Vmess_Path
          value: "/vm6hliu66"
        - name: Share_Path
          value: "/v2link"
